### ISSUE TITLE
UpdateBounds when viewport not started (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1038]
Hi,

I have an usecase, in which i need to calculate the distance of a new model as following:
var newModel = new Model3D...(Transform(Model1Bound_Distance + Model2Bounds_Distance))
This must happen before the RenderEngine is started.

Actually I have two options.
1.) I can call UpdateBounds(...) after adding a model. 
  But to late: Bounds are only set when rendering is active.
2.) I patch your source when I apply the geometry. And force setting the bounds.

Getting the bounds of a complex "groupmodel3d" in the wpf-world is working, even when the rendering is not started.

I need help with this.

Thanks

**Comment by holance** [comment]
I suggest you to call UpdateBounds, this way is more efficient and you can even do it after the model is loaded.

**Comment by holance** [comment]
You cannot get the BoundsWithTransform, since it depends on its parent node. It only updates during rendering.

If you really need this, you have to manually calculate the TotalModelTransform of the model follow its scene graph tree.

If you knows there is no transform applied on its parent, use Geometry.Bound.Transform(TransformMatrix) to get the transformed bound.

**Comment by gregorsGit** [comment]
ComputeTransformMatrix() is working.
This makes it much easier.

Flow and calculate the scene graph tree is to expensive/complicate.
Thanks.
