### ISSUE TITLE
Set per-vertex colour

### ISSUE THREAD

**Issue by MrJox** [helix-toolkit/helix-toolkit#1062]
Apologies if same question already exists, could not find one.
So I have a hex grid where hex is an object. So grid is made of hex objects (models). 
The goal is to have hexes have different initial colours set not through materials but through vertex colours (that's due to feature to change hex colour on mouse click on that hex).
It should work sorta like this:

You load in few images, based on those images tool "compiles" a hex grid map whereas each hex has a pre-calculated colour. I know this can be done with material but the point is, user should be able to change the hex colour by picking the colour he wants and clicking on the hex to change it's colour.

This is where I want to write hex colour changing code. Material does not work because none of sender or event args provide a set-able material property but instead - Color property.

`private void OnHexPressed_Mouse3DDown(object sender, MouseDown3DEventArgs e) {  }`

Additional info:
1. No textures are used;
2. No textures hence no big dial with materials as they will only set the colour;
3. Performance is a big dial, we work with a grid of 720 rows on 1016 columns;
4. Hex Grid is only a set of hex objects (a model made of 6 vertices with no TexCoords or anything else but vertex positions)

I'm looking forward to any alternative approaches if vertex colour is not a solution here.

**Comment by holance** [comment]
You can use MeshGeometry3D.Colors to set per vertex color, then use VertColorMaterial to display per vertex color.
Maybe you can attach some image about the grid you are talking about and how effect you want to achieve?

**Comment by MrJox** [comment]
I'm using Helix.Wpf.SharpDX
Below you can see what I currently render
![image](https://user-images.githubusercontent.com/22772586/51026089-cd023200-159e-11e9-81df-603cfad6004a.png)
Here's the way I do the rendering:
`            var modelList = new List<BatchedMeshGeometryConfig>();
            foreach (var hex in grid) {
                var builder = new MeshBuilder(false, false);
                var polygon = layout.GetPolygonCorners(hex);
                builder.AddPolygon(polygon);
                var hexItem = builder.ToMeshGeometry3D();

                modelList.Add(new BatchedMeshGeometryConfig(hexItem, Matrix.Identity, 0));
                lineBuilder.Add(true, polygon.ToArray());
            }

            HexGrid = modelList;
            Lines = lineBuilder.ToLineGeometry3D(false);`

This is the goal (first screen is launch grid and second is the same one but edited by user) (p.s. this is a photoshop):
![image](https://user-images.githubusercontent.com/22772586/51026361-5dd90d80-159f-11e9-92a3-93ea9bc13f52.png)
![image](https://user-images.githubusercontent.com/22772586/51026402-7d703600-159f-11e9-81dc-a11c978395ac.png)

For allowing the user to draw on hexes I plan to use HitTest. In theory this should replace polygon vertex colours with one in current brush tool.

Going to test the MeshGeometry3D thing.
And thanks for the reply :)

**Comment by MrJox** [comment]
Also, any example of how to properly set per-vertex colours?
The one example I could find uses texture coordinates however I dont have&need them

**Comment by holance** [comment]
First, the BatchGeometryModel3D is not designed for this kind of use. Simply use MeshGeometryModel3D.

Second, you may want to do layered rendering, instead of put everything into one mesh. For example, use only one quad for entire background, and only draw lines for your hex as a background hex layer. Make sure to merge shared vertices to reduce duplication. Then use separate mesh to draw hex with different colors. Number of layer depends on how frequent the mesh changes or number of colors.

For similar meshes, you can try to use instancing to reduce draw calls. 
Since your hit test is on a grid, you can do your own hit test instead of using octree, which is overkilled. 

You may also consider using a texture (Wrapping) to render the base layer grid instead of drawing so many lines to improve performance.

**Comment by MrJox** [comment]
A little of clarification:
So let's put aside line drawing for now, that's not crucial;
You suggest to put all hexes into a single MeshGeometry3D object? That would mean the grid mesh is a solid object so I cannot get access to a distinct hex cell on a grid?
How then will I be able to change the hex cell colour? Plus, as far as I know if vertices are shared, their colour will blend together onto the surface so this means I won't have a per-hex unique colour. If I set a new colour in the hex cell, nearby cells will blend with this cell's colour, isnt it?

**Comment by MrJox** [comment]
Actually I got it working somehow lol. I thought shared vertices affect neighbour faces and blend colour? Unless I didn't remove duplicates
![image](https://user-images.githubusercontent.com/22772586/51058889-547d8e80-15fb-11e9-9e3e-6beebd7556e7.png)

**Comment by holance** [comment]
That's why you need second layer to render the cell with different color. Otherwise each time you try to change one color, you have to rebuild the entire grid will BatchGeometryModel3D.
 Currently the BatchGeometryModel3D is designed to handle static mesh only. 

If you think the performance is Ok, then you can try to use only one layer to render everything and update the big mesh each time a vertex color is changed.

**Comment by MrJox** [comment]
I no longer use BatchedGeometryModel3D. Instead I use MeshGeometryModel3D just as you suggested.
The only reason it seems to work properly is because I do not remove duplicated vertices.
