### ISSUE TITLE
Apply CuttingPlaneGroup to existing elements in scene

### ISSUE THREAD

**Issue by EmilPoulsen** [helix-toolkit/helix-toolkit#1064]
First off, thanks for a great library. Really impressive and powerful stuff.

### Question:
Is there a way to apply `CuttingPlanes` to elements without having to have them as children to `CuttingPlaneGroup`? The way I understand it is that both the `CuttingPlanes` and the `Visual3d` objects to cut need to share the same parent `CuttingPlaneGroup`. Like this:

```
CuttingPlaneGroup cutGroup = new CuttingPlaneGroup();
Plane3D pl1 = new Plane3D(new Point3D(0, 0, 0), new Vector3D(0, 1, 0));
cutGroup.CuttingPlanes.Add(pl1);
var teaPot = new Teapot();
cutGroup.Children.Add(teaPot);
htViewport.Children.Add(cutGroup);
```

Is there a way to automatically apply a `CuttingPlaneGroup` to all elements in the scene, or do I have to "rebuild" all children and add a `CuttingPlaneGroup` parent?

Thanks again!

**Comment by holance** [comment]
Actually you can do your own cut plane instead of relaying on the CuttingPlaneGroup.
CuttingPlaneGroup basically create a new Cut mesh for each children and assign it back to the children.
You can do the exactly same thing for any of your mesh without the CuttingPlaneGroup.

Just look at the [source code](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf/Visual3Ds/Composite/CuttingPlaneGroup.cs) for how to create new mesh with a cut plane. It should be fairly simple.

**Comment by EmilPoulsen** [comment]
thanks once again @holance !! you're the best

ok to close issue, that solves my problem
