### ISSUE TITLE
Make touch input gesture binding configurable and/or allow custom CameraController

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#1074]
In situations (like mine) where you only have two touch points or if you don't need/want the user to rotate the camera but enable panning with just one finger, it would be nice to be able to configure the touch input bindings as it is possible with the mouse:

```
<TouchBinding Command="hx:ViewportCommands.PanRotate" Gesture="PanGesture" />
<TouchBinding Command="hx:ViewportCommands.PinchZoom" Gesture="PinchGesture" />
<TouchBinding Command="hx:ViewportCommands.PanTranslate" Gesture="TwoFingerPanGesture" />
```
The example above would also re-introduce combined zooming and panning, which was the default behavior in the past (pre 2.x). 

Alternatively or additionally, it would maximize flexibility if custom CameraControllers would be possible.

What do you think?

**Comment by holance** [comment]
I have been thinking about custom CameraController support just like the Core project. However, since Viewport3DX provides all the properties to config CameraController, it becomes difficult to separate CameraController from the Viewport3DX. I will do some investigate and see what's the best way to do it without too many breaking changes.

Suggestion is welcome.
