### ISSUE TITLE
Moving a few cubes in SharpDX results in high GPU load

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#1148]
Hi, attached you can find a sample project, in which four cubes are animated by changing the transformation matrix. The resulting GPU load is about 30 % which is very high. Here is a screenshot of the task manager:
![2019_05_07_16_57_08_Task_Manager](https://user-images.githubusercontent.com/18352639/57310185-a6d24600-70e9-11e9-9f5e-74f1afa7f9e2.png)

Are there any suggestions, how i can drop the GPU load? In my real application i have more moving objects of different geometries (so instancing does not help) and this results in CPU load of about 99 %. I need to use the ElementHost (the same way as in the example) and i can't use swap chain rendering, since i have overlay controls.

Thanks for any help!

[WindowsFormsApp1.zip](https://github.com/helix-toolkit/helix-toolkit/files/3153261/WindowsFormsApp1.zip)

**Comment by holance** [comment]
What's your screen resolution?

**Comment by climber03** [comment]
My screen resolution is 1920x1200 and i run the given sample in maximized mode.

**Comment by holance** [comment]
Well, the GPU usage has nothing to do with how many objects are moving in the scene. It purely related to rendering. Moving objects are done in CPU. Since you are using Winform and wrap the WPF, it causes extra GPU usage. Also, WPF D3DImage also has worse performance compare to the swapchain.

Basically updating the Viewport in 60FPS already have 30% GPU usage. I don't think there is any solution for it.

**Comment by climber03** [comment]
Hi, thanks. I adapted the sample and use a SceneNodeGroupModel3D in the view model and in the XAML i use a Element3DPresenter which is bound to the SceneNodeGroupModel3D. I added the scene nodes from the created cubes to the SceneNodeGroupModel3D and then update the ModelMatrix of the items, as you suggested. Unfortunately these changes had no impact on the performance...

**Comment by holance** [comment]
Which performance your referring to? Scene node helps with CPU, not GPU. Are you still using Transform 3D for animation?

**Comment by climber03** [comment]
Both, CPU and GPU. CPU load is very low, so this is not a problem. No, i don't use Transform3D anymore, i directly set the ModelMatrix of the SceneNodes. Ok, these changes are dealing with the CPU-load and thats not a matter of concern. Do you see any other options to decrease the GPU load (e.g. reducing the frame rate, ...)?

**Comment by holance** [comment]
Any particular reason to worry about the 30% GPU load? The only solution is using swapchain. But it won't help too much because screen resolution has big impact on GPU load. 

You can try to reduce your animation FPS, so the viewport will not refresh at 60FPS. 
Disable any anti-aliasing such as MSAA and FXAA, etc. 
Do not use Winform to wrap the WPF, and implement the Winform rendering using HelixToolkit.SharpDX.Core.

**Comment by climber03** [comment]
Hi, I made some more tests with the following result: When i only add one very big cube which fills the whole screen, and then animate the cube (as before), the GPU load is about 50 % :(
The 50 % (or respectively 30 %) are in the sample app, in my real app i have some more meshes and the resulting GPU load is about 99 % which results in a very lagging rendering.

**Comment by holance** [comment]
What's the GPU usage if turn on the Swapchain?

How many lights in your scene? Usually one directional light is enough.

Are you using a lot of overlay UI on top of Viewport? Remove all of them and check the GPU usage.

**Comment by haruby511** [comment]
This GPU is mobile model. The mobile GPUs are using lower power, lower performance. They are obviously slower than desktop models even though latest one.
