### ISSUE TITLE
Nuget install does not work

### ISSUE THREAD

**Issue by afrogonabike** [helix-toolkit/helix-toolkit#125]
Hi,

I've tried to install Sharp HelixToolkit.Wpf.SharpDX via nuget and does not work.  For some reason it installs version 2015.1.474 of SharpDX which expects the same version of HelixToolkit.Wpf.  What is installed is 2014.2.414.0 of Wpf.  I've tried uninstalling and installing manually via the package manager console but get the same problem.  When I install HT.Wpf it says "Installing 'HelixToolkit.Wpf 2015.1.474' but I still get version 2014.2.414.0.

I may be doing something wrong, but I can't work out what.

Tim

**Comment by HIMISOCOOL** [comment]
Can confirm the Nuget package HelixToolkit.Wpf.SharpDX has the dependancy HelixToolkit.wpf (>=2014.2) uses a higher version than it says required
![image](https://cloud.githubusercontent.com/assets/1725300/6519585/189ac18e-c41b-11e4-8319-ebbb8bc2c130.png)

**Comment by HIMISOCOOL** [comment]
I got a working version by cloning the github and then manually changing the version of HelixToolkit.Wpf to 2014.2.9.1 because the cloned version had 2014.2.1.1 which was not okay for anything other than the demo (weird).

This is my reference list now
- HelixToolkit.Wpf (project manually changed version fields to 2014.2.9.1)
- HelixToolkit.Wpf.SharpDx (project)
- PropertyTools
- PropertyTools.Wpf
- SharpDX
- SharpDX.D3DCompiler
- SharpDX.Direct3d11
- SharpDX.DXGI

anything not a project should be obtainable from nuget
