### ISSUE TITLE
How to eliminate jaggies in SharpDx latest version(v.2.10.0)?

### ISSUE THREAD

**Issue by maharada2** [helix-toolkit/helix-toolkit#1284]
Attach a screen capture of my app.
![jaggy](https://user-images.githubusercontent.com/59012971/72037681-5fd4ca00-32e2-11ea-83e4-d5262246ef0b.PNG)

Jaggy is occurring where shadows and objects overlap.
I want to know how to get rid of this jaggy.

I found the following web page.
･[https://helixtoolkit.userecho.com/communities/1/topics/1143-sharpdx-why-does-my-model-look-better-when-using-the-deferred-rendertechnique-instead-of-eg](url)
･[https://github.com/helix-toolkit/helix-toolkit/issues/311](url)
･[https://github.com/helix-toolkit/helix-toolkit/issues/306](url)

From the above contents,
I think that it can be solved by using "delayed rendering" and
modifying the "SampleDescription" of "DPFCanvas.cs".

But now latest HelixToolkit.Wpf.SharpDX(v.2.10.0),
"SampleDescription" of "DPFCanvas.cs" does not exist.
And "RenderTechniquesManager" or "RenderTechnique" also do not exist,
I do not know how to specify the rendering equivalent to [https://github.com/helix-toolkit/helix-toolkit/issues/306](url).

How to specify in the latest version(v.2.10.0)?

**Comment by maharada2** [comment]
I see.
Is there any other way to eliminate such jaggy in 2.x?
(Is there a solution other than using deferred rendering?)

**Comment by holance** [comment]
Can you provide the sample model and your shadow set up?
Or you can try to tune the shadow map parameters.

**Comment by maharada2** [comment]
Sorry, I can't isolate the problem right away.

"Shadow map parameters" is ....
```
<hx:ShadowMap3D
	x:Name="shadowMap"
	LightCamera="{Binding Camera}"
	Resolution="{Binding ShadowMapResolution}" />
```

And ViweModel...

```
this.ShadowMapResolution = new Size( 2048, 2048 );
```

**Comment by holance** [comment]
Please provide your model as well. Seems like your binding light camera to your camera, which is wrong. Light camera should be the light direction used to cast shadow, not your actual camera.

**Comment by maharada2** [comment]
Sorry for the late reply,
I will upload a sample that can confirm the problem.
[TEST.zip](https://github.com/helix-toolkit/helix-toolkit/files/4058407/TEST.zip)

**Comment by maharada2** [comment]
I am using DirectionalLight3D as below...
```
<hx:DirectionalLight3D
    Direction="{Binding Camera.LookDirection}"
    Color="{Binding DirectionalLightColor, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
```
"Camera" bound to Direction is an actual camera.
And no other light source is used.

In this case, does the light direction used to cast shadows not match the LookDirection of the actual camera?

**Comment by holance** [comment]
[TEST.zip](https://github.com/helix-toolkit/helix-toolkit/files/4080164/TEST.zip)
Here is the example for the shadow map I modified based on your example. Working with shadow map is that easy, following things need to be considered.

1. Your model is way to big for shadow map size, you need to make sure your scene can fit into the shadow map.
2. You need to use a secondary directional light without binding to camera look direction, otherwise there will not be any shadow because your light always light up the face you are looking at.
3. You need to set `GeometryModel3D.IsThrowingShadow` to `true` for the model you want to cast shadow. Then you need to set `Material.RenderingShadowMap` to `true` for the model you want to render the shadow.
4. You need to properly set the shadow map paramters such as distance and OrthoWidth to proper value depends on your scene size.

**Comment by holance** [comment]
![Annotation 2020-01-18 010256](https://user-images.githubusercontent.com/905577/72661401-4bea3180-398e-11ea-8eed-1391954d2fdc.png)

**Comment by maharada2** [comment]
Thank you for TEST.zip.
It had shadow jaggies removed.

I checked the operation with the provided code, but I do not understand what the Distance and OrthoWidth of ShadowMap3D mean.
Please let me know if you know the reference document or URL.

（My goal was to get rid of jaggies, and I found that reducing the model size was effective.
　Thank you.）

**Comment by holance** [comment]
http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/
This is the tutorial for shadow map implementation.
