### ISSUE TITLE
PointGeometryModel3D vs translucent planes with diffuse and phong materials

### ISSUE THREAD

**Issue by Forester-** [helix-toolkit/helix-toolkit#1292]
Hi!

HelixToolkit.Wpf.SharpDX 2.10.0

I suppose color blending for translucent PhongMaterial and points model has a bug.

Please take a look on the next image.
![image](https://user-images.githubusercontent.com/1488127/72688039-b7f6a200-3b14-11ea-8505-0e7dcee65982.png)
On the left side we have two translucent planes (blue and red) and points between the planes. The planes use DiffuseMaterial.
On the right side we have two translucent planes (blue and red) and points between the planes. The planes use PhongMaterial.
![image](https://user-images.githubusercontent.com/1488127/72688102-394e3480-3b15-11ea-96ea-df0ab91842f2.png)
The points cross red plane.
![image](https://user-images.githubusercontent.com/1488127/72688125-5d117a80-3b15-11ea-8efe-a6657c40f2b5.png)
And one more screenshot
![image](https://user-images.githubusercontent.com/1488127/72688147-87633800-3b15-11ea-9d81-b09ba716dd89.png)

I expect the points on left and right sides should have similar kind of black color. But on side of phong material planes some points are blue and some points are red (and red points became invisible under red plane). 

The source code for this case is here https://github.com/Forester-/HTKX/tree/master/HxPointsBlending

**Comment by holance** [comment]
You did not setup lighting correctly. Diffuse material uses fake lighting, PhongMaterial needs a light to light up the object. And you are setting one with diffuse color, one with ambient color, and they are definitely not the same thing.

Besides, PhongMaterial will not light up back surface since the surface normal is pointing towards the camera.

[HxPointsBlending.zip](https://github.com/helix-toolkit/helix-toolkit/files/4084451/HxPointsBlending.zip)

**Comment by holance** [comment]
![Annotation 2020-01-19 204420](https://user-images.githubusercontent.com/905577/72699285-870a7300-3afc-11ea-8505-61a0c8ec7fb1.png)

**Comment by Forester-** [comment]
Got it.
Thank you!
