### ISSUE TITLE
Wheel zoom with cursor without mouse down

### ISSUE THREAD

**Issue by bhairav-thakkar** [helix-toolkit/helix-toolkit#1337]
ZoomAroundMouseDownPoint requires a mouse down even with the scroll wheel.. Is it possible to zoom around mouse point without mouse down?

Further, the mouse down point must be on a drawn object. Is it possible to zoom around a point hitting on empty space?

**Comment by chrkon** [comment]
Hi @bhairav-thakkar, 
is this still an open question?

I have tested this today with the WPF Example **CameraControlDemo** and I found no problem. I was able to zoom at the mouse position without a mouse down event. And also a zoom to empty space is possible.

This will work if the property `ZoomAroundMouseDownPoint`is set to `True`. Otherwise the Viewport is zoomed into the center.

**Comment by holance** [comment]
Close this issue for now. Reopen if needed.
