### ISSUE TITLE
Torus class TubeDiameter Property binding fails in WPF UserControl 

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1419]
I created a user control containing a TorusVisual3D object inside HelixViewport3D. Everything works. But when I bind to the TubeDimaterProperty in XAML or in code my program crashes. I am not very advanced in WPF. I was not able to pinpoint the exact issue. Since other properties work well and binding in code also fails for the TubeDimaterProperty, I am inclined to think the problem is with the TubeDiameter property. I looked into the source code, as I indicated I am not very advanced in WPF.

`<UserControl x:Class="Torus2020A.TorusUserControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:hx="clr-namespace:HelixToolkit.Wpf;assembly=HelixToolkit.Wpf"
             xmlns:local="clr-namespace:Torus2020A"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
        <DockPanel>
            <hx:HelixViewport3D x:Name="UCTorusView"
                            ModelUpDirection="0,1,0"
                            ZoomExtentsWhenLoaded="True"  
                            ShowCoordinateSystem="True" 
                            PanGesture="LeftClick">
                <hx:TorusVisual3D x:Name="UCTorus"  
                TorusDiameter="{Binding Path=UCTorusDiameter, RelativeSource={RelativeSource AncestorType=UserControl, AncestorLevel=1}}"
                TubeDiameter="{Binding Path=UCTubeDiameter, RelativeSource={RelativeSource AncestorType=UserControl, AncestorLevel=1}}"
                ThetaDiv="{Binding Path=UCThetaDiv, RelativeSource={RelativeSource AncestorType=UserControl, AncestorLevel=1}}"
                PhiDiv="{Binding Path=UCPhiDiv, RelativeSource={RelativeSource AncestorType=UserControl, AncestorLevel=1}}"
                />
            </hx:HelixViewport3D>
        </DockPanel>
    </Grid>
</UserControl>`

This is the failing XAML (removing TubeDiameter or assigning a value to it works):

This is the binding in Code:

`// var b = new Binding("UCTubeDiameter");
            // b.RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(UserControl), 1);
            // BindingOperations.SetBinding(UCTorus, TorusVisual3D.TubeDiameterProperty, b);`

I tried Visual Studio 2017 with Framework Version 4.6 and 2019 with 4.7. The results were the same. Thank you for a wonderful contribution. Please let me know if you need the whole solution.

**Comment by chrkon** [comment]
Dear ikonuk,
it is difficult to find an error without the full source. I assume, that you have take a look into the Example folder of the HelixToolkit.Wpf solution. There is a sample for using the Torus class. 

I take this example and add an UserControl based on your xaml code. I have also added the dependency properties for the UC[...] variables into the code behind file of the UserControl. Then I add a Slider to the main Window and Bind the UserControl Property UCTubeDiameter with this slider.

Everything works as you can see in this picture:

![image](https://user-images.githubusercontent.com/456192/95503028-0dc4f000-09ab-11eb-96a8-17bac9ad8874.png)

You can find the source code for this in my github fork (Branch: '**issue/TubeDiameterBinding#1419**'): 
[HelixToolkit forked by chrkon](https://github.com/chrkon/helix-toolkit/tree/issue/TubeDiameterBinding%231419)

**Comment by ikonuk** [comment]
Attached please find the offending code (Solution) created with Visual Studio 2017. If you change the TubeDiameter entry in the TorusUserControl.XAML to TubeDiameter="1", it works. Thank you very much for 
[torus20.zip](https://github.com/helix-toolkit/helix-toolkit/files/5350990/torus20.zip)
your attention and time.

**Comment by chrkon** [comment]
Hi ikonuk,
I get the following Error message: `HelixToolkit.Wpf.HelixToolkitException: 'Torus must have a Diameter bigger than 0'`

To prevent this error I have added a default value to the dpendency properties in file **TorusUserControl.xaml.cs**. This can be done by setting the _PropertyMetadata_ parameter in the dp registrations.

To solve our problem with this user control we only need to set a default value for the UCTubeDiameterProperty 
```
        public static readonly DependencyProperty UCTubeDiameterProperty =
            DependencyProperty.Register("UCTubeDiameter", typeof(double),
                            typeof(TorusUserControl), new PropertyMetadata(1.0));
```
I wonder why the error message gives a wrong hint. As you found for yourself the problem is not in the TorusDiameter, but in the TubeDiameter property. So it could be an issue in the TorusBuilder. I will take a look on it in the next days.

For now I hope this information helps to go on with your project.

**Comment by ikonuk** [comment]
Thank you very much indeed. Yes, it does solve my problem. Please do let me know if you end up releasing a new version or making changes.

Best regards;

I.Konuk

**Comment by ikonuk** [comment]
I apologize I closed the issue too quickly. 

Unfortunately defining a default value at DependencyProperty registration does not solve the problem. The binding does not crash the program now but it does not work at all. TubeDiamaeer property does not respond to the changes in the property it is linked to as if there is no binding. All other properties do respond. 

By the way, I am using the binding to do animations by changing my local property by a function. Thank you again very much for your attention and time. I impressed by and grateful to the HelixToolkit project.

**Comment by chrkon** [comment]
Dear I. Konuk,
could you give me a sample of your failing code? 

In the [sample I mentioned yesterday](https://github.com/helix-toolkit/helix-toolkit/issues/1419#issuecomment-705770392) I have made a binding against a Slider and it is working fine (see [Line 15](https://github.com/chrkon/helix-toolkit/blob/issue/TubeDiameterBinding%231419/Source/Examples/WPF/ExampleBrowser/Examples/Torus/MainWindow.xaml)).

**Comment by ikonuk** [comment]
In your example a second Torus object is placed on the MainWindow. Slider is bound to this control not the user control.

I am attaching a new example with TorusDiameter  (myTorusDoamter property in my ModelView) bound to the UserControl which works. If you replace it with "myTubeDiameter" which is my property in my ModelView, you will see nothing happens.

[Torus2020A.zip](https://github.com/helix-toolkit/helix-toolkit/files/5357630/Torus2020A.zip)

**Comment by chrkon** [comment]
Hi I. Konuk,
I will take a look to your second sample, but your comment is wrong.

In [Line 15](https://github.com/chrkon/helix-toolkit/blob/issue/TubeDiameterBinding%231419/Source/Examples/WPF/ExampleBrowser/Examples/Torus/MainWindow.xaml) the User Control is added to the Main Window and the binding is between the Slider Value and the UserControl property.
The second Torus is part of the user control.

**Comment by chrkon** [comment]
Hello I. Konuk,
everything is fine. I found the problem. It is just a typo in the binding!
![image](https://user-images.githubusercontent.com/456192/95634234-b0ec3700-0a89-11eb-95f8-14bd4336cf98.png)
Just change the second 'U' into an 'u'. Then the Tube Diameter will work.

Kind regards,
Christof

**Comment by ikonuk** [comment]
I am embarrassed. I was wrong on both counts! I looked at my code so long, and so many times. I never noticed the capital "U".ain 

Thank you again very much. I am very sorry to waste your time. Sincere apologies! Thanks to all participants again for a beautiful and very useful project.

I. Konuk

**Comment by chrkon** [comment]
@holance Dear Lunci,
I have checked the source code and I was able to help I.Konuk on this issue #1419 without changing the code base of the helix toolkit. I would like to pass on his thanks to all other contributors and of course to you!

On checking the sources I have found the folowing inconsistence in the Torus handling.

- In the TorusVisual3D code file ( [Line 66](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.Shared/Visual3Ds/MeshVisuals/TorusVisual3D.cs#L66) ) the Dependency Property Setter of `TubeDiameter` checks the value `greater or equal` to zero. ( value >= 0.0 )
But in the `MeshBuilder.AddTorus` method ( [Line 3024](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L3024) ) a TubeDiameter == 0.0 will throw a HelixToolKit Exception. 

I think the Exception text should be changed to "Torus must have a Tube Diameter bigger than 0" because problem is on the Tube diameter and not on the Torus Diameter. 

Changing the check in the TorusVisual3D file from `>= 0.0` to `> 0.0` has not fixed the problem of I. Konuk. But since I found a workaround, I don't know if this is really a bug that needs fixing.

Kind regards,
Christof

**Comment by holance** [comment]
@chrkon I think it is a bug in `MeshBuilder.AddTorus`, should throw exception if diameter <= 0.

**Comment by chrkon** [comment]
@holance Tube diameter < 0 is not possible, because the setter in the TorusVisual3D will not allow this. But 0.0 is possible in the TorusVisual. So this will throw the exception. 

As a test I had changed the if clause in the TorusVisual3D.TubeDiameter setter to `value > 0` to prevent this exception. But this was not helpful. The torus was not drawn at all.

**Comment by holance** [comment]
@chrkon MeshBuilder is a separate component, it can be used separately.

**Comment by chrkon** [comment]
@holance Yes, you are right.

**Comment by chrkon** [comment]
@holance I have made another test for this issue. I just have removed the exception from the AddTorus method.

And now the original code from I. Konuk (without defining a default value for the tube diameter) is running. 

These are my changes in the MeshBuilder class (Line 3024):
```
            else if (tubeDiameter <= 0.0)
                Debug.WriteLine("Torus must have a Tube Diameter bigger than 0");
                //throw new HelixToolkitException("Torus must have a Tube Diameter bigger than 0");
```
I saw 2 lines in the debug output. So the "tubeDiamater == 0.0" case came two times, but after this everything was OK.

I would suggest to remove the exception and the debug code and just do nothing in case of tube diameter == 0. If the diameter is zero, nothing will be drawn.
