### ISSUE TITLE
RenderBitmap with custom size I get black bitmap

### ISSUE THREAD

**Issue by miquik** [helix-toolkit/helix-toolkit#1439]
I’d like to take screenshot of current viewport; I used RenderBitmap extension method and I gave correct result. But resolution is low so I use RenderBitmap method with width/height (is it correct?) but I obtain a completely black bitmap after saving to file

**Comment by chrkon** [comment]
Hi @miquik, I have no trouble to render the bitmap with a higher resolution. 

To reproduce your Issue, I have added some code to the ModelViewer Example in my fork repository. You can find the code in my Fork: [chrkon -helixToolkit Fork, Issue 1439](https://github.com/chrkon/helix-toolkit/tree/issue/%231439_RenderBitmap-Custom-Size)

[Example: ModelViewer/MainViewModel.cs](https://github.com/chrkon/helix-toolkit/blob/6e64a0b5e442703b330908eecb51e841b39620ed/Source/Examples/WPF/ExampleBrowser/Examples/ModelViewer/MainViewModel.cs#L192) 
```
       private void CopyBitmapHiResolution()
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            var bitmap = Viewport3DHelper.RenderBitmap(
                                            this.viewport.Viewport, 
                                            1920.0, 1080.0,
                                            new SolidColorBrush(Colors.White), 1);
            try
            {
                Clipboard.Clear();
                Clipboard.SetImage(bitmap);

                stopwatch.Stop();
                this.ApplicationTitle = string.Format(TitleFormatString, this.CurrentModelPath, 
                    $"(rendered as HD bitmap into clipboard in {stopwatch.ElapsedMilliseconds} ms)");
            }
            catch (Exception)
            {
                this.ApplicationTitle = string.Format(TitleFormatString, this.CurrentModelPath, "(storing in clipboard failed)");
            }
        }
```
I have added the stopwatch to show the delay in rendering with a new resolution.

In the example it takes up to 3,1 seconds to create the HD bitmap. Be sure, that your bitmap is already rendered before you save the file. 

Creating a bitmap with same resolution is fast, because the view is already shown on the screen. Creating a bitmap with a different resolution takes more time, because the whole Model has to be created and rendered a second time.

Kind regards,
Christof

**Comment by miquik** [comment]
Thank you very much for your answer,
I forgot to say that I am using Viewport3DX and I already use "SharpDX" version of your code above. But that gives me completely black bitmap result

**Comment by chrkon** [comment]
Hi @miquik, 
thank you for this important information. I have added similar code to the `FileLoadDemo` project in the HelixToolkit.SharpDX solution in [my HelixToolKit fork](https://github.com/chrkon/helix-toolkit/tree/issue/%231439_RenderBitmap-Custom-Size-SharpDX).

Example: [FileLoadDemo/MainViewModel.cs](https://github.com/chrkon/helix-toolkit/blob/871804f06b40cab1a4da3e141cce7009352ba583/Source/Examples/WPF.SharpDX/FileLoadDemo/MainViewModel.cs#L211)

```
        private void CopyAsHiResBitmapToClipBoard(Viewport3DX viewport)
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            var bitmap = ViewportExtensions.RenderBitmap(viewport,1920,1080);
            try
            {
                Clipboard.Clear();
                Clipboard.SetImage(bitmap);
                stopwatch.Stop();
                Debug.WriteLine($"creating bitmap needs {stopwatch.ElapsedMilliseconds} ms");
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
        }
```
This code works on my system. The redering is much faster than in the WPF sample. It takes only 420ms to render the view in HD resolution.

This is the Image in original window size:
![RenderBitmapWindowSize](https://user-images.githubusercontent.com/456192/97921182-e0c1ee00-1d5a-11eb-9fb0-81d12e6e3cd3.png)

And this is the same image rendered in HD resolution:
![RenderBitmap1920x1080](https://user-images.githubusercontent.com/456192/97921243-f20afa80-1d5a-11eb-8971-ba10f32885a5.png)

Please take a look into the sample and check if it works on your PC, too. 

Kind regards,
Christof

**Comment by chrkon** [comment]
Hi @miquik, just a short note: 
_The Helix ToolKit source code is not 'my code'. I am just a volunteer, who want to help other developers if they have issues with this fantastic ToolKit. I have used this Toolkit in different projects and this is my way to give back something to the project._ 

Please give a feedback if you have solved the issue. 

If you can not find the error, please create a small project which reproduces the same issue and attach it to your post. Finding errors is easier, if you can debug some code.

Kind regards,
Christof

**Comment by miquik** [comment]
Hi @chrkon , sorry for my late reply .. I was trying to solve another problem before try your solution.
I think I’ve done as you suggested but I still get same result. My viewport3dx is in the center of a Grid with two Splitter (one on the left and one on the right side) don’t know if this can be the problem

**Comment by chrkon** [comment]
Hi @miquik I can not see any reason, why the splitters should create this issue. But searching for the bug would be much more effective, if I could see the your code. 

You can add the code as zip file or you can create an own github repository just for the sample. Then I could take a closer look into this issue.

Have you got cloned the branch from [my Helix-ToolKit fork](https://github.com/chrkon/helix-toolkit/tree/issue/%231439_RenderBitmap-Custom-Size-SharpDX)?  And have you run the `File Load Demo` example from the SharpDX .sln solution in this branch? 

This code will copy the generated bitmap into the clipboard. So it is easy to check the result. Just insert the bitmap into a viewer or into the  `paint` App.

**Comment by miquik** [comment]
Hi @chrkon I found the problem. I had EnableSwapChainRendering property set true in Viewport3DX. 
Probably this is an expected behaviour, if so, I'm sorry because I haven't study deeper the framework (well to be honest there is very poor documentation) before start coding

**Comment by chrkon** [comment]
Hi @miquik, I don't think that this issue is an expected behaviour. In my oppinion you have found a real bug. 
And you don't have to apologize for "not knowing everything". Noboby can know everything. And as you already mentinoned the documentation of the Helix Toolkit is also not perfect.  But every contributor uses parts of his sparetime to push this project. Even your comments are part of this process. 

I think it is an important information you found. And as you can see, just a single different setting can changed the whole behaviour. 

Now we can reproduce this bug. That is the first step to solve it. Many thanks for finding it!

**Comment by miquik** [comment]
Sorry don't know if I have to keep open this or close

**Comment by chrkon** [comment]
I suggest to hold it open, until we have resolved the bug.

**Comment by chrkon** [comment]
@holance I have taken a deeper look into this bug and it is really strange.
I can reproduce this behaviour, if I just add `EnableSwapChainRendering = "true"` in the XAML file. 

But it will **not happen**, if I use property binding `EnableSwapChainRendering="{Binding SwapChainProperty}"` in the XAML file.  Of course the property is initially set to "true" in the ViewModel. So it should be the same behaviour.

Have you got an Idea?

P.S.: @miquik: Perhaps this is a workaround for you?

**Comment by miquik** [comment]
@chrkon yes I can do this way ... I was thinking about  directly set `EnableSwapChainRendering` Property to false before RenderBitmap and then set again to true

**Comment by chrkon** [comment]
@miquik You don't need to set the property to false. Just set the property to true in the ViewModel and don't change it.  
I don't know why this works, but I have found this on my tests. The bug only occurs, if you use `ÈnableSwapChainRendering = "True"` in the XAML code.

**Comment by miquik** [comment]
Still have same problem if I set `EnableSwapChainRendering = true` in View (Window) constructor. It works if flag is set in Loaded event. The problem is related to "when" this property is computed internally

**Comment by chrkon** [comment]
@miquik: You are right. the issue seems to be related to the timing.

And the workaround is not setting `EnableSwapChainRendering = true` in the constructor or somewhere else in the code behind file. The workaround I suggested is: use `Binding`!

Create a property in the code behind file:
```
public bool SwapChainWorkaround {get; set;} = true;
```
and use this line in the XAML file:
```
EnableSwapChainRendering="{Binding SwapChainWorkaround}"
```
I know that this should be the same, but the timing seems to be different.
