### ISSUE TITLE
Is it possible to free up MeshGeometry3D data once it has been pushed to the GPU for rendering?

### ISSUE THREAD

**Issue by aparajit-pratap** [helix-toolkit/helix-toolkit#1449]
This is more of a question rather than an issue. Is it possible to free up `MeshGeometry3D` data from system memory once it has been pushed to the GPU for rendering? If so, is there an easy/recommended way of doing this?

**Comment by holance** [comment]
Geometry data is still being used for hit test

**Comment by mjkkirschner** [comment]
@holance - if no hit testing is required is it a possibility?

**Comment by holance** [comment]
Not for now, since geometry is separated from models/scene nodes, and hit test is controlled at model/scene node layer.

Each geometry can be bind or set to model/scene node at runtime, so disposing geometry data may break this kind of design.

We may be able to create some kind of special geometry to handle this special usage. But it's impossible for current implementation.

**Comment by aparajit-pratap** [comment]
Thanks @holance. Closing.

**Comment by holance** [comment]
Reopen to implement this feature.

**Comment by holance** [comment]
You can use `Geometry3D.SetAsTransient()` to mark the geometry, so its data will be cleared once loaded into GPU.

Following are the restriction: View only, no hit test support, geometry must not be shared with multiple models. Must call `Geometry3D.SetAsTransient()` before attaching to a Model3D or the Model3D has not been attached to a viewport.
