### ISSUE TITLE
RectangleVisual3D do not work (show) when Normal=(1,0,0)

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1461]
I came across this strange behavior in a project I am working. I prepared the attached small example to illustrate the problem.

I. Konuk

[rectangletest.zip](https://github.com/helix-toolkit/helix-toolkit/files/5578080/rectangletest.zip)

**Comment by chrkon** [comment]
Hi @ikonuk, thank you for this message.  - @holance : **Unfortunately I have to confirm this bug.** 

But perhaps you can use the following workaround until the bug is fixed:
Instead of `Normal = new Vector3D(1, 0, 0)` you could use `Normal = new Vector3D(1, float.Epsilon, 0)` .
I know that this is not the same, but `float.Epsilon` is defined as `1.401298E-45`. And this is very close to zero. I have checked this with your sample and it works. 

I take this issue and I will take a closer look on it. 

And many thanks to you for answering questions of other users. This is a way to improve such an open source project. 

Kind regards,
Christof

**Comment by ikonuk** [comment]
Christof: 

Thank you very much again. Thank you also for the workaround.

I really like this project. I will try to do my best to help others. I have limited C# and WPF experience. I am a mathematician and engineer and normally code in C++. Please do not hesitate to contact me If there are any tasks or questions along those lines.

Thank you again for the kind words. Happy Holliday season to everybody.

I. Konuk

**Comment by chrkon** [comment]
Dear I. Konuk,
I have found the real reason for this bug. It is really more a mathematical issue than a software bug. 

If you use the normal vector to define the rectangle plane you need a second vector to define a perpendicular direction for one of the edges. Otherwise the orientation for length and width is not clear and we can't construct the rectangle. 

In `RectangleVisual3D` you can define the `LengthDirection` vector. This vector is (1,0,0) by default. And if both vectors (`normal`and `LengthDirection`) are parallel the cross product will come to 0.0 and the calculation of the rectangle mesh fails. [(see the source here](https://github.com/helix-toolkit/helix-toolkit/blob/17fb3bca62253e5c4041f9bca7dcf4ed62bcc47b/Source/HelixToolkit.Wpf.Shared/Visual3Ds/MeshVisuals/RectangleVisual3D.cs#L197))

I have explained my fix in the description of the PullRequest #1470 . ([bug fix here](https://github.com/helix-toolkit/helix-toolkit/pull/1470/commits/523f61b8a3bb8a2ff0b854c01a0008c9549b5a9d#diff-e632eb58846f113dfbe770578165012ad93e9e009f7d225e9372fda4bb422543)) 
But perhaps you have a better idea to solve this?

Kind regards,
Christof

**Comment by ikonuk** [comment]
Christof:

Thank you for your time again. I feel embarrassed. Of course, two parallel vectors cannot define a plane. I should have thought about it.

This is NOT a bug in my opinion. The fact that it does not trough an exception is credit to the developer(s). I will close this case if you do not have any objection.

Kind regards

Ibrahim

**Comment by chrkon** [comment]
Hi Ibrahim,
you don't need to feel embarrassed. How could you have known that you also had to set the length direction vector?
I think this should be part of the documentation. 

But you mentioned a possible exception. I agree, that setting both values to parallel vectors would be a kind of an argument exception. Do you think we should throw an exception on this? 

Personally I don't like such exceptions. But a hint for the Developer would be helpful. But up to now I have not Idea how to solve this. At least I agree, that we can close this issue.

Kind regards,
Christof

**Comment by ikonuk** [comment]
Dear Christof:

I think the current design is just fine. It simply ignores the request. As you indicated when the documentation is finalized, a brief warning (that normal and the direction vectors cannot be colinear) would be sufficient.

Thank you for your attention again. have a nice day.

Ibrahim
