### ISSUE TITLE
Binding to Point3DCollection with DataTemplate3D

### ISSUE THREAD

**Issue by KKauK** [helix-toolkit/helix-toolkit#1479]
Hi,

I' m trying to bind to my Point3DCollection using the DataTemplate3D with no success.
If I drop the binding and set the values in xaml everything works. Any help is apprechiated!

```
<local:DataTemplate3D x:Key="MyTemplate">
<ht:MeshGeometryVisual3D>
<ht:MeshGeometryVisual3D.MeshGeometry>
<MeshGeometry3D Positions="{Binding Positions}"></MeshGeometry3D>
<!--<MeshGeometry3D Positions="-100,100,85 -100,-100,85 100,-100,85 100,100,85"/>-->
</ht:MeshGeometryVisual3D.MeshGeometry>
</ht:MeshGeometryVisual3D>
</local:DataTemplate3D>

```
...
```
<local:ItemsVisual3D x:Name="MyMesh"
                                 ItemTemplate="{StaticResource MyTemplate}"
                                 ItemsSource="{Binding MyVisualisationItemsCV}"/>

```

**Comment by ccHanibal** [comment]
Hi @KKauK,

the issue seems to be easy to fix.

It has to do with the way a binding is converted back into XAML. The DataTemplate3D currently can not handle a Binding that is represented as an element rather than an inline expression. Why in this case the binding gets converted differently compared to other cases I can not tell. I will provide a pull request fixing this.
