### ISSUE TITLE
Quick changing texture

### ISSUE THREAD

**Issue by vavilov** [helix-toolkit/helix-toolkit#148]
Hello everyone.
​
Basic WPF 3D allows to draw to texture in runtime, using RenderTargetBitmap in material. So, drawing in this bitmap instantly affects on mesh texture.
In Helix Toolkit the visible texture changes only after re-attaching model, or using ​AttachMaterial​() in MaterialGeometryModel3D. But these actions finally use something like this "..​.DiffuseMap.ToByteArray()​", and it totally wastes speed of execution;​

​
Is there some way to overcome this and/or bind Bitmap (or it's pure byte[]) to DiffuseMap?​
Or Helix Toolkit have fast method to chenge texture?​
Thanks!

**Comment by objorke** [comment]
Is this related to the SharpDX component?

**Comment by vavilov** [comment]
No, i meant Helix Tookit possibilities without changing/exploring SharpDX code.

**Comment by ikeough** [comment]
We've considered doing the same, but there is no way that we have found currently to push the `byte[]` directory to the buffer. You could make your own version of `MaterialGeometryModel3D`, with a property to store your `byte[]` and an overidden version of `AttachMaterial()` which sets the buffer using your `byte[]` instead of converting the provided `BitmapSource`. 

We are currently creating the `BitmapSource` objects on the fly from a `byte[]`, without using an image file from disk, but the creation of the `BitmapSource` only to have it unpacked back into a `byte[]` does cost a bit.

**Comment by vavilov** [comment]
Thank You.
