### ISSUE TITLE
apply post effect mesh outline to some models in groupModel3d

### ISSUE THREAD

**Issue by mjkkirschner** [helix-toolkit/helix-toolkit#1488]
we have a fairly simple setup using a single viewport and group model with bound items:
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Views/Preview/Watch3DView.xaml#L113

we do have a custom mesh type with vertex shader/pixel shader - as well as use of depth bias on some geometries.

I can't seem to get the post effect mesh outline to work on any of the geometries in the group. - I am using code like

`geo as OurCustomModel3d.PostEffects = "EffectName"` - but the effect does not show.

If I add a helix primitive to the top level under viewport3dx - the effect displays.

Using helix 2.11
(I saw the change log about a white background so I tried with black and no improvement was seen)

Please feel free to close this and redirect to gitter if this is not a bug.

**Comment by holance** [comment]
Do you have the link on setting up the custom vertex shader?

**Comment by mjkkirschner** [comment]
Hi @holance - we add the custom shader and technique here to the effects manager:
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/ViewModels/Watch3D/DynamoEffectsManager.cs#L92

and use it here:
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/ViewModels/Watch3D/DynamoGeometryModel3D.cs#L95

Please let me know if that was what you were asking for?

**Comment by holance** [comment]
@mjkkirschner Instead of creating an new technique, try to add your custom shader as new pass. Otherwise you need to add additional passes in your technique to support post effects.
https://github.com/helix-toolkit/helix-toolkit/blob/eddb4f9805edbd7c9a1839f168bc3b78016134b2/Source/HelixToolkit.SharpDX.Shared/ShaderManager/DefaultEffectsManager.cs#L285

You can copy and paste those effect pass into your technique.

**Comment by mjkkirschner** [comment]
@holance -thanks got this working! I still need to find out exactly which passes I need, but it works!
