### ISSUE TITLE
How can I zoom in and out in Helix Toolkit and SharpDX

### ISSUE THREAD

**Issue by MichaelInsberg** [helix-toolkit/helix-toolkit#1560]
I try to zoom in and out in the code behind.

```
<hx:Viewport3DX
            Name="Viewport"
            BackgroundColor="Black"
            Camera="{Binding Camera}"
            EffectsManager="{Binding EffectsManager}"
            ShowViewCube="False">
</hx:Viewport3DX>
```
```
public OrthographicCamera Camera { get; }

public void ZoomIn()
{
            var newPosition = new Point3D(Camera.Position.X, Camera.Position.Y, Camera.Position.Z * 1.5);
            Camera.AnimateTo(newPosition, Camera.LookDirection, Camera.UpDirection, 500);
}       

```
but nothing changed.

The Camera.Position.Z was changed but not the view of the application.

Any suggestions?

Greeting Michael

**Comment by eriove** [comment]
The `Width` property is controlling how much you see in the view when you are using the `OrthographicCamera`.

**Comment by MichaelInsberg** [comment]
Hi thanks for the tip I will try this.

I also tried PerspectiveCamera and 

```
        public void ZoomIn()
        {
            var newPosition = new Point3D(Camera.Position.X, Camera.Position.Y, Camera.Position.Z*1.01);
            Camera.MoveCameraPosition(newPosition);
        }
```
But this has also no effect. Why does the camera don't move?

Greeting Michael

**Comment by holance** [comment]
You can use `Viewport3DX.AddZoomForce` to zoom in or out.

**Comment by chrkon** [comment]
I think there is an issue with zooming the `orthographic camera` in combination with `CameraMode` property. 
In the `ZoomHandler` class the different camera modes are handled different for both camera types. 

See Methods `Zoom`, `ZoomByChangingCameraWidth` and `MoveCameraPosition` in source files:
[ZoomHandler.cs (SharpDx.Core)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.SharpDX.Core/Controls/ZoomHandler.cs),
[ZoomHandler.cs (Wpf.Shared)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.Shared/Controls/CameraController/ZoomHandler.cs) and 
[ZoomHandler.cs (UWP)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.UWP/Controls/MouseHandlers/ZoomHandler.cs)

Why do we have three different files for the same function?

**Comment by holance** [comment]
> I think there is an issue with zooming the `orthographic camera` in combination with `CameraMode` property.
> In the `ZoomHandler` class the different camera modes are handled different for both camera types.
> 
> See Methods `Zoom`, `ZoomByChangingCameraWidth` and `MoveCameraPosition` in source files:
> [ZoomHandler.cs (SharpDx.Core)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.SharpDX.Core/Controls/ZoomHandler.cs),
> [ZoomHandler.cs (Wpf.Shared)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.Shared/Controls/CameraController/ZoomHandler.cs) and
> [ZoomHandler.cs (UWP)](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.UWP/Controls/MouseHandlers/ZoomHandler.cs)

Because the MouseGestureHandler is platform dependent.

**Comment by chrkon** [comment]
I can understand that the ZoomHandler is platform dependent, but why ist the CameraMode "WalkAround" not possible with orthographic camera?

**Comment by holance** [comment]
@chrkon Because of how the projection matrix math works. While walking around, you want objects closer to camera to become bigger (zooming in), and objects far from camera still keep relative small (basically the perspective effect). However, orthographic camera renders all objects in viewport the same zooming factor. And orthographic camera uses width to control the zoom in/out. Walkaround by changing camera position does not make sense for orthographic camera.

**Comment by chrkon** [comment]
@holance I think the "walkAround" mode could be usefull in othographic camera, too. If you set the nearPlaneDistance to a small positive value, everything near to the camera is not shown anymore. In this case you could walk through the scene (without changing the view width) and you can "enter" 3D nodes (walk through the meshes). 

I use the Helix Toolkit in a technical context and I have to use the orthographic camera because the lengths and angles should be visualized correrectly. We analyse the inner side of a volumic object (like pipes and tanks) and generate the meshes based on the measured values. Now we want to simulate a walk through the scene. My idea was to move the camera through the scene.

I would create a specialized CameraController class to solve this special requirement, but unfortunately the CameraController and the ZoomHandler in the SharpDX.Core part are sealed. Do the classes need to be sealed?  
In the "UWP" part and the "Wpf.Shared" part both classes are NOT sealed.

Kind regards,
Christof
