### ISSUE TITLE
New Helix Toolkit wpf new dependencies

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1837]
I noticed while updating Helix Toolkit.wpf from 2.21.1 to 2.22.0 that it is loading new dependencies:

System.Buffers.4.5.1
System.Numerics.Vectors.4.5.0
System.RunTime.CompilerServices.Unsafe.4.5.3
System.Memory.4.5.4
Microsoft Extensions.Logging. Asbatractions.6.0.0

Could someone explain why we need these new components? Also do we need a new dynamic library to run our executable?

I.Konuk

**Comment by ikonuk** [comment]
I just found out that these dependencies are due to using .NET Framework 4.8.1. It is not due to Helix Toolkit. Anyone can comment the implications of these new components being required with .NET Framework 4.8.1?

**Comment by holance** [comment]
If you only use HelixToolkit.wpf, you don't need to update to 2.22, since there is no change on HelixToolkit.wpf project.
Those new dependencies are probably from `Microsoft Extensions.Logging. Asbatractions` since we changed the logging in Helixtoolkit, but only used by Helixtoolkit sharpdx projects.
