### ISSUE TITLE
How can I convert HelixToolkit.Wpf.SharpDX.Geometry3D to HelixToolkit.SharpDX.Core.Geometry3D

### ISSUE THREAD

**Issue by KaivnD** [helix-toolkit/helix-toolkit#1845]
I'm make a 3d app with `HelixToolkit.Wpf.SharpDX`, which is very nice toolkit. Now I'm try to make a offscreen renderer for object preview, and I found a [offscreen render](https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/Examples/SharpDX.Core/OffScreenRendering/Renderer.cs) in example code.

But I can't put `Geometry3D` in wpf app to `Renderer` because `HelixToolkit.Wpf.SharpDX.Geometry3D`  and  `HelixToolkit.SharpDX.Core.Geometry3D` is two class defined in different assembly.

My question is how to convert these objects, or is there a `OffScreenRenderer` for wpf kind?

thanks.

**Comment by holance** [comment]
Created a PR to move ViewportCore into shared project, so you can refer to the offscreen render example and use the viewport core from HelixToolkit.SharpDX.Wpf project. You probably need to modify few namespaces in the example so everything should be refer to the namespace under `HelixToolkit.SharpDX.Wpf` instead of `HelixToolkit.SharpDX.Core`.

If you don't want to use Nightly build, another workaround is to simply copy the `ViewportCore.cs` and `ViewportCoreProperties.cs` source file into your own project and fix the namespaces, then you can use it.

**Comment by KaivnD** [comment]
@holance wow! this is so nice, you are my favorite person in this website!
