### ISSUE TITLE
Regarding asynchronous requirements for loading models

### ISSUE THREAD

**Issue by GreenShadeZhang** [helix-toolkit/helix-toolkit#2189]
```csharp
  var modelPath = Package.Current.InstalledLocation.Path + $"\\Assets\\ElectronBotModel\\{modelName}";
  var newScene = _importer.Load(modelPath);
```
When I use model loading, I need to load it repeatedly, but I think loading will consume time, but the framework does not seem to provide asynchronous capabilities. Is it possible to add some asynchronous loading capabilities.

**Comment by holance** [comment]
Due to the wpf framework limitation, wpf framework elements are not allowed to be created in different thread unless it is freezed. You can set `_importer.Freeze = true` and use another thread to load the model. 
Or use helixtoolkit sharpdx version and load model using scene nodes, which are not depending on wpf framework.
