### ISSUE TITLE
 BUG: HelixToolkit.SharpDX MeshGeometryModel3D bounds

### ISSUE THREAD

**Issue by IgorGrechka** [helix-toolkit/helix-toolkit#296]
Hi guys!

I found a bug (I think so) in the calculation of the `Bounds` property of `MeshGeometryModel3D` when `OnGeometryChanged` is emitted! I loaded model which has **31917** positions, but when Helix calls `BoundingBox.FromPoints(this.Geometry.Positions.Array)` (in GeometryModel3D class) to calculate BoundingBox corners, `Array` method returns array size of **32768**. So as result wrong BoundingBox will be returned. Please see screenshot bellow:

![bug](https://cloud.githubusercontent.com/assets/1829604/18091036/f084d638-6ecf-11e6-8f52-1d6ab4da447f.PNG)

I think `Array` method allocates memory (I am not shure). All values in array after 31916 are equil zero. 32768 is the closest exponent 2, than is bigger 31916. I think issue is in file CollectionExtensions.cs in static class `ArrayAccessor`.

But I don't know how to fix this!

**Comment by Iluvatar82** [comment]
I checked the BoundingBox creation with the use of the *Collection.Array Attribute and I think @IgorGrechka is right. The Count of the returned Array is always 2^x so that all *Collection Elements fit into it.

A fix would be to modify the call to this:
`            var b = BoundingBox.FromPoints(this.Geometry.Positions.ToArray());
`
But I assume there was a reason for the Array attribute in the first place...

**Comment by holance** [comment]
Has been fixed in new version.
