### ISSUE TITLE
SharpDX 11

### ISSUE THREAD

**Issue by ehtick** [helix-toolkit/helix-toolkit#300]
At this moment the samples are not compatbile with SharpDX latest version (3.02) and DX11.
Is this going to be updated?

**Comment by SiNeumann** [comment]
I really would wish this to happen since it would get rid of the deployment headaches I currently have(mainly installing DirectXEndUserRuntime June 2010 or making sure it is installed).

But it's not that simple SharpDx 2.6 to 3.x had breaking changes and SharpDX.Toolkit is still not updated to SharpDx 3.x currently there are two conflicting pull requests https://github.com/sharpdx/Toolkit/pull/4 and https://github.com/sharpdx/Toolkit/pull/3 . Both are not really usable(I tried). So basically we will have to wait for SharpDx to update their ToolKit and then try to move. 
IF this is done the sharpDX.Toolkit page says
"The Toolkit is deprecated and is no longer supported."
But in the next line
"The current code of the Toolkit in this repository is no longer working with the latest branch of SharpDX. We need to work on cleaning/test/upgrade to the latest version of SharpDX."

**Comment by RobJellinghaus** [comment]
SiNeumann, what problem did you have with the #4 PR?  Did you try the binaries provided by SmartK8 in the discussion thread?

**Comment by SiNeumann** [comment]
We'll I have to admit the same had when trying to update ShapDx in HelixToolkit in without the SharpDx.Toolkit https://github.com/helix-toolkit/helix-toolkit/pull/302 . Guess I didn't try long enough. The main problem was that all the Structures (Color4, Rectangle,Vector2,3,4 etc)went into SharpDx.Mathematics.dll but are still in namespace SharpDX, so on build I ran into lots off issues. 

Anyway preferable would be to have all external dependencies via NuGetPackages, in my opinion a unmerged PR will cause to much headache in  deployment.  
As I stated in my PR #302 moving to SharpDx 3.0 would enable us to implement Directx12 .

**Comment by ehtick** [comment]
I use several libraries to that us SharpDX, for an example sharpOVR and then the problem really starts.
Am look at WPFDXInterop from microsoft, would like to keep wpf and use a higher directx version (wpf does 9) and then also try to use the oculus inside that.

But i think SharpDX is better to use for the future.

**Comment by JeremyAnsel** [comment]
Since it was upgraded to the latest version of SharpDX (3.1.1, #390), could this be closed?

**Comment by holance** [comment]
Closed
