### ISSUE TITLE
Polygon Point examples for testing new Triangulator

### ISSUE THREAD

**Issue by Iluvatar82** [helix-toolkit/helix-toolkit#322]
Hi there, I wanted to help out a little and I wrote a **SweepLinePolygonTriangulator**, which should have a runtime of O(n * log n), compared to the available **CuttingEarsTriangulator** (O(n^2)).

Now I need to test the Triangulator before requesting a pull and therefore I ask you, if you know a source of polygon point-data, I didn't find anything yet.

I need to enhance some things before I submit it but the first test shows it's working.
Thank you

**Comment by Iluvatar82** [comment]
I need to verify the result is valid, but in a comparison with the **CuttingEarsTriangulator**, the new **SweepLinePolygonTriangulator** seems to work a lot faster.

I created a List of 5,000 Points, that form a circle, and let both Triangulators run, see for yourself:
![5000points_comparison_10x](https://cloud.githubusercontent.com/assets/3210590/19886809/4890897c-a025-11e6-9f05-94ac61a5cfbb.jpg)

The second screenshot is taken from a 50,000 Point Circle examlpe:
![50000points_comparison_100x](https://cloud.githubusercontent.com/assets/3210590/19886811/4d3d81b4-a025-11e6-9f13-55341f49e7e5.jpg)

As you can see, while the old algorithm almost needs 100 times longer for 10x the points, my new algorithm just runs a little more than 10 times longer.

**Comment by glasspusher** [comment]
if you still need data, I can generate some for you.

**Comment by Iluvatar82** [comment]
Thank you,

I already wrote a simple generator myself, which creates points on a circle with a random radius to get nice results.
I think it's enough for the testing purposes and I already found a bug (I think I need to rewrite my polygon-splitting). But if you can provide a few examples, that would be great!

**Comment by glasspusher** [comment]
do you just want circles.  I can get you any shape. 2d or 3d.

**Comment by Iluvatar82** [comment]
Any **simple** 2d polygon would be great

**Comment by glasspusher** [comment]
I'll try to get something out tonight.
\

**Comment by Iluvatar82** [comment]
Thank you!
I hope I can fix my bugs soon, just found another one. But I think it will be fixed soon.

**Comment by 0x53A** [comment]
Hi @Iluvatar82, would it be possible to upload an early version / send a WIP pull-request? 

We are developing a 3D application and are looking for a new triangulator due to performance issues with our current one.
I would like to trial it, and if I find any issues I could upload the offending polygons.

(Otherwise I could try to extract a few polygons and upload them if you want, but they are mostly boring.)

Is there a specific format you want the data in?

**Comment by Iluvatar82** [comment]
@0x53A I can do that after work today.
But the demo project generates polygons that are sometimes triangled in a wrong way. I think I know where the problem is, but need to debug it until I can call it "finished"

I don't need any specific format for the data, text or XML is ok I think...

**Comment by 0x53A** [comment]
Ok so for the test data I can try to provide:

We have 3D models of buildings:

![image](https://cloud.githubusercontent.com/assets/4236651/19932923/026307f2-a112-11e6-969d-a12618ea4781.png)

My plan was to extract all faces from these models, flatten them to 2d and export them.

Most of them will be just rectangles, but some have inner holes or are in general a bit more complex:

![image](https://cloud.githubusercontent.com/assets/4236651/19933146/bb52ec5a-a112-11e6-9985-1b53844cfb33.png)

![image](https://cloud.githubusercontent.com/assets/4236651/19933170/c751fad2-a112-11e6-94da-a5facb20a938.png)

![image](https://cloud.githubusercontent.com/assets/4236651/19933191/d9166528-a112-11e6-9f07-b47ed2858a89.png)

Would these help you?

I will see if I can do it today, if not then probably tomorrow.

**Comment by Iluvatar82** [comment]
Well at them moment I didn't implement a handling of holes, but I think this may only be a simple extension (I might be wrong though) to the current algorithm.

**Comment by 0x53A** [comment]
For the first step I could ignore the holes and just export the outer loop.

**Comment by objorke** [comment]
very cool, I look forward to see this!!
For sample polygons, what about using text outlines? See
https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/Examples/WPF/ExampleBrowser/Examples/ExtrudedText/Extensions.cs
Could we remove the dependency to Triangle.NET with the sweep line triangulator?

**Comment by Iluvatar82** [comment]
Ok, I have enhanced the Triangulator a bit. Most of the time it works fine, sometimes it is still buggy though. I need to look into that.

Here is an example from my demo project (random amount of circle-points from 15 - 2000) with a random radius from 3-5):
![example](https://cloud.githubusercontent.com/assets/3210590/19948527/4577b2fa-a14d-11e6-8079-9fae37f3138c.JPG)

I also managed to get the Triangulator to work with the TextExtension (which i temporarily implemented in my demo as well), but without the holes and still with some problems (I am going to debug this tomorrow or maybe soon after):
Font: Times new Roman (visible characters EfF)
![ef_bug](https://cloud.githubusercontent.com/assets/3210590/19948578/80287ba0-a14d-11e6-8295-d4416fe58d46.JPG)

Most characters are triangulated correctly (like the lowercase **f**), but some have a problem at the top left corner...

**Comment by Iluvatar82** [comment]
Sorry, I forgot to mention, that we can't remove the Trinagle.net dependency yet. I need to work on a solution for the holes and make it bug free

**Comment by Iluvatar82** [comment]
Ok, so I fixed the "bug" with the characters (the CuttingEarsTriangulator also had it's problems). The algorithm doesn't allow the first polygon-point to be equal to the last polygon-point, so it wasn't really a bug, but I implemented a check for that case.
The example below shows the result:
![characters_fixed](https://cloud.githubusercontent.com/assets/3210590/19983748/7f013ca8-a20b-11e6-8873-a12418896926.JPG)
I will add the possibility to use the triangulator also with **holes** (by making the polygons simple) and try to implement a much simpler polygon splitting approach than I have implemented now.

I think if this is done we're ready to go public (btw: you can find the current version in [my fork of the toolkit](https://github.com/Iluvatar82/helix-toolkit))

**Comment by Iluvatar82** [comment]
I rewrote my polygon-splitting today, which is so much easier to understand (and only a few lines) and it is also faster than my previous approach (50k Points-Circle needs 365ms now).
Also there seem to be no errors in the triangulation anymore...

Let's implement some holes, oh yes

**Comment by Iluvatar82** [comment]
Screenshots from the tests.
Please note, that a circle seems to be a "very fast" to triangulate polygon! I tested other polygons, and they take up to 8-10times as long, but maybe this might be another possibility to enhance the algorithm. But tbh, I think it's already much better than the previous one...
Compare for yourself (status bar at the bottom of the window....)
OLD:
![cuttingears50kcircle](https://cloud.githubusercontent.com/assets/3210590/20019745/10d25fe6-a2ce-11e6-9f98-e7d7240c244b.JPG)
NEW:
![sweepline50kcircle](https://cloud.githubusercontent.com/assets/3210590/20019765/26314532-a2ce-11e6-94bd-6e783ed6db86.JPG)
Please note, that there are axactly as many triangles in the first pic, than in the second one! They are just so small in the first pic, that you can't see them! In the second pic almost every triangle crosses from left to right, that's why you see so much red. I render every triangle's edge as a red line....

**Comment by holance** [comment]
Nice!

On Fri, Nov 4, 2016, 12:37 PM Franz Spitaler <notifications@github.com>
wrote:

Screenshots from the tests.
Please note, that a circle seems to be a "very fast" to triangulate
polygon! I tested other polygons, and they take up to 8-10times as long,
but maybe this might be another possibility to enhance the algorithm. But
tbh, I think it's already much better than the previous one...
Compare for yourself (status bar at the bottom of the window....)
OLD:
[image: cuttingears50kcircle]
<https://cloud.githubusercontent.com/assets/3210590/20019745/10d25fe6-a2ce-11e6-9f98-e7d7240c244b.JPG>
NEW:
[image: sweepline50kcircle]
<https://cloud.githubusercontent.com/assets/3210590/20019765/26314532-a2ce-11e6-94bd-6e783ed6db86.JPG>
Please note, that there are axactly as many triangles in the first pic,
than in the second one! They are just so small in the first pic, that you
can't see them! In the second pic almost every triangle crosses from left
to right, that's why you see so much red. I render every triangle's edge as
a red line....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/helix-toolkit/helix-toolkit/issues/322#issuecomment-258528029>,
or mute the thread

**Comment by Iluvatar82** [comment]
If I allow holes in the Polygon, do you think it is ok to just assume they are "valid", meaning they are **all completely inside** the Polygon and **non-overlapping** or should I first check for those conditions?
Maybe I just start assuming they are valid and add checks (optional?) later?

**Comment by Iluvatar82** [comment]
I did test the triangulator with a lot of different generated polygons, so I think examples are not needed anymore. Thank you

**Comment by EmilPoulsen** [comment]
awesome work @Iluvatar82 
was there any follow up on the polygons with holes? 

sorry for writing in a closed issue

**Comment by Iluvatar82** [comment]
Hi @EmilPoulsen, thank you very much.
I think a working solution that handles holes as well should be included in the helix-toolkit, see #339 for more info.

**Comment by EmilPoulsen** [comment]
sweet, thanks's a lot @Iluvatar82 !! will try it out.

**Comment by Iluvatar82** [comment]
You're welcome :)

**Comment by TykmaSnicholson** [comment]
@Iluvatar82 I'm attempting to use the triangulator with fonts that are stored as a simple line segment points list.  I made sure to build the list as a continuous line segment and I order them so that they are CCW (if I left them CW, I was getting negative index values from the triangulator and getting very invalid meshes.)  Now if I only add the base character outline, the result looks great; the holes also look fine if I only render them.  However, when I add the holes to the base character, I usually get at least one gap, sometimes more as seen here:
![TriangulatorError01](https://user-images.githubusercontent.com/51199934/58633936-f4d90480-82b7-11e9-9384-a55c28cdbd77.JPG)

Depending on which font I use, they can end up being much worse:
![TriangulatorError02](https://user-images.githubusercontent.com/51199934/58633965-06baa780-82b8-11e9-97f9-88e3138f860b.JPG)

I'm assuming I'm doing something wrong either with the way I build the final mesh with the results or with the data supplied to the triangulator, but I've burnt quite a few hours on this already and I'm just not seeing it.  Do you have any idea what might be causing these issues?

Thanks!
