### ISSUE TITLE
(Helixtoolkit.SharpDX)Rotate geometry is sluggish

### ISSUE THREAD

**Issue by holance** [helix-toolkit/helix-toolkit#327]
If zoom in the geometry very large in viewport and start doing quick mouse rotation, the rotation becomes sluggish every few seconds. GC issue? Race condition?

**Comment by holance** [comment]
Infinite rotate does not have this issue. Seems it happens only using mouse to do fast rotation.

**Comment by BetaRavener** [comment]
I have been looking into this problem before, but couldn't find the cause. At least I think it's the same problem, but instead of "becoming sluggish every few seconds", for me it was "becoming sluggish/unusable after few moments of camera rotation".  I have profiled my aplication with Visual Studio and what I found was that during camera rotation, there was increasing gap between issuing command and graphics card actually executing it. The gap can be though of as lag between input and screen output, and so with longer camera rotation the lag became worse and worse. 

Now, I think part of the issue is that Helix is picking up only integrated Intel HD4000 (I have mobile NVidia but it's in Optimus topology and so helix discards it because it doesn't have screen output). Computing power of that Intel graphics is just bad and it simply can't render scene 60FPS. Still, I would expect the scene to lag "constantly", say 10 FPS, instead of crawling from 60FPS to unusable.

However, one lead I found and it might be important piece to solving this: The way that Helix measures drawing time in SharpDx part is just plain wrong. It uses CPU timer to time how much rendering of the frame took BUT what it really does is just measuring how long it took to issue those commands into buffer. So the Helix sees that scene is redrawing fine at high framerate but the graphics card is crying from all the work it is getting.

Anyway, if this one is the same as I experienced, it is really critical to solve as any complex scene is impossible to view.

**Comment by holance** [comment]
I will look into this issue as well. While using mouse rotate, the OnRendering routine keeps falling into these two sections:
https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf.SharpDX/Controls/DPFCanvas.cs#L614
https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf.SharpDX/Controls/DPFCanvas.cs#L628

It may be some kind of timing issue and queued up the dispatcher or the composite renderer.

**Comment by holance** [comment]
Close issue for now. This particular sluggish issue for me has been fixed in #331. @BetaRavener please open anther issue if you still experience the performance issue.
