### ISSUE TITLE
Move MeshBuilder to shared project

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#350]
- avoid maintaining two very similar codes
- See the `CuttingEarsTriangulator` and `SweepLinePolygonTriangulator` classes.

**Comment by Iluvatar82** [comment]
On behalf of simplifying (/merging) the code,
what about implementing e.g. the SweepLinePolygonTriangulator in the shared WPF Project and "make it usable" in SharpDX (since it's also referenced).
Maybe we could create a generic version that is usable in WPF (Point class) and SharpDX (Vector2 class)? Is it even possible without a lot of problems? (e.g. **DotProduct** vs. **Dot** - function-calls)...

**Comment by Iluvatar82** [comment]
Ok sorry I just saw that already done in a cool way for the SweepLinePolygonTriangulator :)

**Comment by Iluvatar82** [comment]
So... I have spent several hours now to merge the two Meshbuilders like you did with the CuttingEarsTriangulator and the SweeplinePolygonTriangulator, but somehow I always get some errors, that look like this:

![errors_cs0433](https://cloud.githubusercontent.com/assets/3210590/20462034/9544e6ec-af10-11e6-8ef3-da5bb06dbe23.JPG)

Does anybody know how to resolve this? I don't know why the MeshBuilder is in the namespace HelixToolkit.Wpf.SharpDX ?!? My merged MeshBuilder class is in the namespace HelixToolkit.Wpf (like your two example-merges).

I have also got many warnings of kind CS0436 which reports conflicting functions (also present in both namespaces). These warnings also occur for the triangulators...

**Comment by Iluvatar82** [comment]
Well I got rid of the error by rmoving all references to **HelixToolkit.Wpf** from the projects.
The meshbuilder is working now but there are a lot of warnings, idk if this is ok or not.

I tested all example projects, both in Wpf and Wpf.SharpDX and they all work.
An exception exists:
It is the fractal demo in the Wpf Example-Browser with the settings "Merger sponge" and a "Detail-Level" above 3. I get a memory out of bounds exception (but that may have been there previously maybe)...

**Comment by Iluvatar82** [comment]
I think everything works now, except some compiler warnings...
I posted a question to stackexchange: [Compiler warning Cs0436](http://stackoverflow.com/questions/40704853/cs0436-compiler-warning-with-a-shared-project)

**Comment by Iluvatar82** [comment]
I think I found an explanation of the problem here:
[Stackoverflow post](http://stackoverflow.com/a/30638495/2252268)
The `...code is incorporated into each assembly that references the shared project...` which means we reference the shared code two times (projec reference HelixToolkit.Wpf and the shared project).

What do we want to do about it (I think we **should**)?

What about a generic implementation and two "dummy"-sub-classes that inherit from the generic solution and set the respective types, but there would be quite some of them, like 5 types or so...

So the proposed solution for the MeshBuilder (can be easily done for the triangulators as well):
in HelixToolkit.Shared:
`public class GenericMeshBuilder<T1, T2, ....>`
in HelixToolkit.Wpf:
`class MeshBuilder : GenericMeshBuilder<T1, T2, ....>` where T1 e.g. System.Windows.Media.Media.Point3D, etc.
in HelixToolkit.Wpf.SharpDX:
`class MeshBuilder : GenericMeshBuilder<T1, T2, ....> ` where T1 e.g. SharpDX.Vector3, etc.
I don't know it it would even work, but I think it would be possible to "directly" reference them via the namespaces...

What do you think?

**Comment by holance** [comment]
I think unless vector3 and vector3D share same interface, otherwise, generic one won't work.

**Comment by Iluvatar82** [comment]
We could use helper functions instead (like SharedFunctions.CrossProduct) to decide which function should be really called...
But if the warnings are ok, I think we don't need it.

**Comment by holance** [comment]
I am also thinking about using extension methods as a adapter as well.

**Comment by Iluvatar82** [comment]
I created a few in the SharedFunctions.

**Comment by holance** [comment]
Warning fixed #367

**Comment by Iluvatar82** [comment]
I think this can be closed since the MeshBuilder is now in the Shared Project.
