### ISSUE TITLE
AddRectangularMesh doesn't reflect light - SharpDX

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#374]
AddrectangularMesh objects doesn't reflect light.

In the below sample code, I add cylinder, rect mesh, quad.
cylinder and quad reflect lights but the rect mesh doesn't.

![image](https://cloud.githubusercontent.com/assets/3082469/20639279/d875325e-b3e4-11e6-8c9f-f9891c481f0b.png)

in the above image, middle black rectangle is the Mesh.

is anything wrong here...?

```
MeshGeometry3D mesh;

var mbuilder = new MeshBuilder();

//Cylinder
mbuilder.AddCylinder(new Vector3(0, 0, 0), new Vector3(10, 10, 10), 2, 32);

//Rectangle mesh
List<Vector3> vl = new List<Vector3>();
vl.Add(new Vector3(0, 0, 2));
vl.Add(new Vector3(10, 0, 2));
vl.Add(new Vector3(0, 10, 2));
vl.Add(new Vector3(10, 10, 2));
mbuilder.AddRectangularMesh(vl, 2, true);

//Quad
mbuilder.AddQuad(new Vector3(0, 0, 0),
    new Vector3(5, 0, 0),
    new Vector3(5, 5, 0),
    new Vector3(0, 5, 0));

mesh = mbuilder.ToMeshGeometry3D();

BitmapSource bSource = new BitmapImage(new Uri(@"C:\Pictures\myimg.jpg"));

MeshGeometryModel3D meshGeoModel3D = new MeshGeometryModel3D();
meshGeoModel3D.Geometry = mesh;
meshGeoModel3D.Material = new PhongMaterial
{
    DiffuseMap = bSource,
    NormalMap = bSource
};
```

**Comment by Iluvatar82** [comment]
Maybe the problem is the lighting here?
I got the same result with the "AddRectangularMesh" and the "AddQuad" function as you did at first.

Just add another light from another direction, that should hopefully fix your problem.
Another possible solution is to replace this:
`//Rectangle mesh
List<Vector3> vl = new List<Vector3>();
vl.Add(new Vector3(0, 0, 2));
vl.Add(new Vector3(10, 0, 2));
vl.Add(new Vector3(0, 10, 2));
vl.Add(new Vector3(10, 10, 2));
mbuilder.AddRectangularMesh(vl, 2, true);`
with this (that should reverse the Normals, maybe it's enough to get correct lighting):
`//Rectangle mesh
List<Vector3> vl = new List<Vector3>();
vl.Add(new Vector3(10, 0, 2));
vl.Add(new Vector3(0, 0, 2));
vl.Add(new Vector3(10, 10, 2));
vl.Add(new Vector3(0, 10, 2));
mbuilder.AddRectangularMesh(vl, 2, true);`

**Comment by mk48** [comment]
Thanks @Iluvatar82 
It worked now, reverse the Normals worked. 

```
List<Vector3> vl = new List<Vector3>();
vl.Add(new Vector3(10, 0, 2));
vl.Add(new Vector3(0, 0, 2));
vl.Add(new Vector3(10, 10, 2));
vl.Add(new Vector3(0, 10, 2));
```

![image](https://cloud.githubusercontent.com/assets/3082469/20645760/8a04d7ec-b48d-11e6-838d-90b2d2943980.png)
