### ISSUE TITLE
How to change a shape value dynamically in SharpDX?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#375]
I used Helix toolkit. It has 'QuadVisual3D' control. I can bind four Point values(Point1, Point2, Point3, Point4) from XML to my view model. When the view model value changes the Quad is also getting changed.

I want the same kind of behaviour in SharpDX.
I just want to change a rectangle size (four corner) dynamically.

What I do now:
Created a 'MeshGeometryModel3D' tag in xml.
Binding the 'Geometry' property with 'MeshGeometry3D' in view model.
Every time creating a new 'MeshGeometry3D' using 'MeshBuilder' and assigning to 'Geometry' property.
I want do to this in a mouse move event.
I feel creating a new object and assigning it in each and every mouse move event is not good practice.

Is there any best way of doing this in SharpDX.

**Comment by holance** [comment]
Usual it won't be an issue unless you experience a performance hit. Then
you need to modify the meshbuilder and meshgeometrymodel3d and put an
object pool into it.

**Comment by Iluvatar82** [comment]
Since you don't want to change "the structure" of your element I would suggest you build yourself a scale matrix to modify the size of the quad (almost certainly built into a matrix class somewhere... I just can't access the code right now).

This way you always keep your initial shape and just modify it's size when transformed to world-coordinates (and later the viewport)

**Comment by mk48** [comment]
Thanks all, as of now I don't face any performance issue. I will go with the current procedure. 
I will try what @Iluvatar82 suggested after sometime, then I will share.
I am closing this now.
