### ISSUE TITLE
Data Template example: Cannot find governing FrameworkElement

### ISSUE THREAD

**Issue by Fendoroid** [helix-toolkit/helix-toolkit#442]
The recently upgraded `DataTemplate3D` class provided with the Data Template example, worked like a charm. However it still generates the error `System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element.` when using bindings inside it. This error doesn't cause problems in many scenarios, but there are few ones where it becomes problematic.
I'm using `DataTemplate3D` to show a collection of `UIElement3D` objects. I wanted those objects to be clickable, so I've overridden the `OnMouseDown(MouseButtonEventArgs)` event handler. However, clicking those object resulted in nothing: the event does not raise. Suspecting that the above mentioned binding error is the cause of this, I've put the UIElement3D object directly in the `HelixViewport3D`, and the event raised normally.
I think `DataTemplate3D` breaks the visual tree, preventing events to pass through it.

**Comment by ccHanibal** [comment]
The binding error messages you see are generated right after the template object gets deserialized from XAML when the bindings do not have a proper binding source yet. Due to the Mesh

**Comment by Fendoroid** [comment]
I've prepared a minimal project reproducing the issue: the red cube raises the event, while the cyan cube (defined by `DataTemplate3D`) does not.
[Example.zip](https://github.com/helix-toolkit/helix-toolkit/files/769653/Example.zip)

**Comment by ccHanibal** [comment]
This seems a bit of "works as designed" by the wpf team.

As far as I understand it (and I'm by far not an expert on this), mouse interaction inside a `Viewport3D` is only passed down in the logical xaml tree if the direct child is an `UIElement3D` because this is the only class that has methods to handle mouse interactions on 3D objects. The `ItemsVisual3D` is derived from `ModelVisual3D` which can not handle mouse interaction, thus can not pass it down to its generated children.

Unfortunately `UIElement3D` can not have children so we can not make another `ItemsVisual3D` with mouse interaction capabilities by deriving from `UIElement3D`.

I guess we could make the `ItemsVisual3D` operate on the `Chldren` collection of its parent `Viewport3D` instead of it's own so that the generated `UIElement3D` objects are direct children of the viewport. But I would consider this more of a hack than a real solution.

On the other hand if you only need the click event you could do that by manually performing hit testing on the viewport in a click handler attached to the viewport. More on how to do that, here: http://csharphelper.com/blog/2014/10/perform-hit-testing-in-a-3d-program-that-uses-wpf-xaml-and-c/

**Comment by Fendoroid** [comment]
Thanks for your help. I may try something to work around this WPF limitation.

**Comment by ccHanibal** [comment]
I just discovered that the only reason the UI interaction logic is not applied is that the bound cube is not present at load time of the viewport. By removing the `ItemsVisual3D` every time it's `Children` collection changes this logic can be enabled for generated items aswell.

Inserting this at the end of `CollectionChanged` and `ItemsSourceChanged` should do the trick - tested myself with your example project above.
```
var viewPort = HelixToolkit.Wpf.Visual3DHelper.GetViewport3D(this);
var index = viewPort.Children.IndexOf(this);
viewPort.Children.Remove(this);
viewPort.Children.Insert(index, this);
```

Will do a pull request some time next week, too.
