### ISSUE TITLE
SharpDX: Instanced Models do not follow the viewports current render technique

### ISSUE THREAD

**Issue by RandomityGuy** [helix-toolkit/helix-toolkit#802]
Hi,
Im having this issue where the models from InstancingMeshGeometryModel3D don't follow the viewports current render technique.
When I change the viewports render technique, all other models except the instances get rendered according to my choice.

**Comment by holance** [comment]
Because the instancing mesh model uses separate technique to render. If you don't need to use the extra instancing parameters, use the mesh geometry model, it can do instancing as well.

In develop branch, the way to change shading types has been changed. You can specify different material to change the shading types including the instancing mesh model.

**Comment by holance** [comment]
Use material to change shading mode #801
