### ISSUE TITLE
TaskCanceledException not caught in OnDetached

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#988]
Please have a look at this:
![https://i.imgur.com/pKweSGL.png](https://i.imgur.com/pKweSGL.png)

Happens when closing the application (WinForms, ElementHost).

**Comment by holance** [comment]
Are you getting this exception when running examples?

**Comment by smischke** [comment]
No, it's just in one of my use cases where I embed a WPF-Control with this control template...

```
  <ControlTemplate>
    <hx:Viewport3DX x:Name="PART_Viewport3DX"
                    Foreground="{TemplateBinding Foreground}"
                    Background="{TemplateBinding Background}"
                    BorderBrush="{TemplateBinding BorderBrush}"
                    BorderThickness="{TemplateBinding BorderThickness}">
      <hx:Viewport3DX.EffectsManager>
        <hx:DefaultEffectsManager/>
      </hx:Viewport3DX.EffectsManager>
    </hx:Viewport3DX>
  </ControlTemplate>
```

...into a WinForms-Window (using System.Windows.Forms.Integration.ElementHost). It's just the behavior that happens when closing the WinForms-Window. 

Also, I think Viewport3DX should have a DefaultEffectsManager assigned by default, so that it's working out of the box (as before). I had to add...

```
      <hx:Viewport3DX.EffectsManager>
        <hx:DefaultEffectsManager/>
      </hx:Viewport3DX.EffectsManager>
```
... in many places and those places I forgot caused unexpected crashes (NullReference). Please don't forget MVVM Nation and VNV Nation. :)

**Comment by holance** [comment]
Because if EffectsManager assigned by default, it causes memory leak(dispose by finalizer). Dispose from UI thread is mandatory to avoid this issue. The proper way is hookup the dispose function with Windows.Closed event.

If you repeatedly open and close the window with viewport, you will see the issue. That's why there is a memoryleaktester program in demos to test the memory leak issue.

**Comment by smischke** [comment]
Thanks for pointing this out. I have to further investigate this in my code. For now, I implemented IDisposable (explicitely) in my control that disposes the effectsmanager. IDispose is wired to WinForms Dispose. Need to check this in WPF-/MVVN world.

**Comment by holance** [comment]
I suspect this is because underlying SharpDX or DirectX issue. I have not found a solution yet. 

Assigning a default effects manager also complicates the resource management. If user bind a custom one, the internal one in viewport contains duplicate unused resources. If there are multiple viewports, the duplication doubles. Usually multiple viewports should share only one EffectsManager to minimize the resource duplication. 

For now, the most easy and clear way is to let user manage the 3D resource lifecycle, not the Viewport itself.

MVVM is based on WPF framework, and WPF itself has its own 3D resource management (I believe it is also managed by a centralized way). So naturally it is hard and complicate to completely follow MVVM if another framework ( such as helixtoolkit sharpdx) uses another layer of rendering resource. 

Also MVVM has performance issue on real-time data streaming and rendering, I would not use MVVM on performance critical code path.

**Comment by holance** [comment]
Please manually dispose the effects manager.
Added [Wiki](https://github.com/helix-toolkit/helix-toolkit/wiki/EffectsManager-Usage) page to clarify EffectsManager usage.
